package Frames;

import Classes.Funcionario;
import ClassesDeEntidades.Livro;
import Paineis.PanelChart;
import Paineis.add_livro;
import Paineis.delete_livro;
import Paineis.edit_livro;
import Paineis.list_livro;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

public class FrameGerente extends javax.swing.JFrame {

    add_livro adbook;
    delete_livro delbook;
    edit_livro editbook;
    list_livro listbook;
    PanelChart pnelChart;

    public FrameGerente() {
        initComponents();

        pnelChart = new PanelChart();
        pnelChart.setSize(600, 300);
        pnelChart.setAlignmentX(LEFT_ALIGNMENT);
        pnelChart.setBounds(10, 10, pnelChart.getWidth(), pnelChart.getHeight());
        getContentPane().add(pnelChart);
        pnelChart.setVisible(false);

        adbook = new add_livro();
        adbook.setSize(890, 300);
        adbook.setBounds(10, 10, adbook.getWidth(), adbook.getHeight());
        getContentPane().add(adbook);
        adbook.setVisible(false);

        delbook = new delete_livro();
        delbook.setSize(890, 300);
        delbook.setBounds(10, 10, delbook.getWidth(), delbook.getHeight());
        getContentPane().add(delbook);
        delbook.setVisible(false);

        editbook = new edit_livro();
        editbook.setSize(890, 300);
        editbook.setBounds(10, 10, editbook.getWidth(), editbook.getHeight());
        getContentPane().add(editbook);
        editbook.setVisible(false);

        listbook = new list_livro();
        listbook.setSize(890, 300);
        listbook.setBounds(10, 10, listbook.getWidth(), listbook.getHeight());
        getContentPane().add(listbook);
        listbook.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_adicionar = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_excluir = new javax.swing.JButton();
        btn_listar = new javax.swing.JButton();
        btn_gerargrafico = new javax.swing.JButton();
        btn_pdf = new javax.swing.JButton();
        btn_atendentes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_adicionar.setText("Adicionar");
        btn_adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_adicionarActionPerformed(evt);
            }
        });

        btn_edit.setText("Editar");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_excluir.setText("Excluir");
        btn_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluirActionPerformed(evt);
            }
        });

        btn_listar.setText("Listar");
        btn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarActionPerformed(evt);
            }
        });

        btn_gerargrafico.setText("Gráfico");
        btn_gerargrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerargraficoActionPerformed(evt);
            }
        });

        btn_pdf.setText("Exportar PDF");
        btn_pdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pdfActionPerformed(evt);
            }
        });

        btn_atendentes.setText("Atendentes");
        btn_atendentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atendentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btn_adicionar)
                .addGap(38, 38, 38)
                .addComponent(btn_edit)
                .addGap(39, 39, 39)
                .addComponent(btn_excluir)
                .addGap(34, 34, 34)
                .addComponent(btn_listar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btn_atendentes)
                .addGap(33, 33, 33)
                .addComponent(btn_gerargrafico)
                .addGap(28, 28, 28)
                .addComponent(btn_pdf)
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(313, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_adicionar)
                    .addComponent(btn_edit)
                    .addComponent(btn_excluir)
                    .addComponent(btn_listar)
                    .addComponent(btn_gerargrafico)
                    .addComponent(btn_pdf)
                    .addComponent(btn_atendentes))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_adicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_adicionarActionPerformed
        adbook.setVisible(true);
        delbook.setVisible(false);
        editbook.setVisible(false);
        listbook.setVisible(false);
        pnelChart.setVisible(false);
        adbook.atualizarTabela();
    }//GEN-LAST:event_btn_adicionarActionPerformed

    private void btn_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluirActionPerformed
        adbook.setVisible(false);
        delbook.setVisible(true);
        editbook.setVisible(false);
        listbook.setVisible(false);
        pnelChart.setVisible(false);
        delbook.atualizarTabela();
    }//GEN-LAST:event_btn_excluirActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        adbook.setVisible(false);
        delbook.setVisible(false);
        editbook.setVisible(true);
        listbook.setVisible(false);
        pnelChart.setVisible(false);
        editbook.atualizarTabela();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarActionPerformed
        adbook.setVisible(false);
        delbook.setVisible(false);
        editbook.setVisible(false);
        pnelChart.setVisible(false);
        listbook.setVisible(true);
        listbook.atualizarTabela();
    }//GEN-LAST:event_btn_listarActionPerformed

    private void btn_atendentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atendentesActionPerformed
        new FrameAtendente().setVisible(true);
    }//GEN-LAST:event_btn_atendentesActionPerformed

    private void btn_pdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pdfActionPerformed

        try {
            Document document = new Document(PageSize.A4, TOP_ALIGNMENT, TOP_ALIGNMENT, 30, TOP_ALIGNMENT);
            PdfWriter.getInstance(document, new FileOutputStream("D:\\listalivros.pdf"));

            document.open();
            PdfPTable tabela = new PdfPTable(7);
            PdfPCell cabecalho = new PdfPCell(new Paragraph("Lista de Livros da Biblioteca"));
            cabecalho.setHorizontalAlignment(Element.ALIGN_CENTER);
            cabecalho.setBorder(PdfPCell.NO_BORDER);
            cabecalho.setBackgroundColor(new BaseColor(100, 150, 200));
            cabecalho.setColspan(7);
            tabela.addCell(cabecalho);
            tabela.addCell("Código");
            tabela.addCell("Nome");
            tabela.addCell("Editora");
            tabela.addCell("Edição");
            tabela.addCell("Àrea");
            tabela.addCell("Ano");
            tabela.addCell("Código Biblioteca");

            //busca todos livros para popular a tabela
            List<ClassesDeEntidades.Livro> list = null;
            Funcionario f = new Funcionario();
            list = f.listartodos();

            for (Livro l : list) {
                tabela.addCell(l.getIdLivro().toString());
                tabela.addCell(l.getNomeLivro());
                tabela.addCell(l.getEditora());
                tabela.addCell(l.getEdicao());
                tabela.addCell(l.getArea());
                tabela.addCell(l.getAno().toString());
                tabela.addCell(l.getIdBiblioteca().getIdBiblioteca().toString());
            }

            document.add(tabela); //adiciona itens na tabela
            document.close();

            File arq = new File("D:\\listalivros.pdf");
            Desktop.getDesktop().open(arq);

        } catch (DocumentException docex) {
            docex.printStackTrace();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FrameGerente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FrameGerente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_pdfActionPerformed

    private void btn_gerargraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerargraficoActionPerformed
        adbook.setVisible(false);
        delbook.setVisible(false);
        editbook.setVisible(false);
        listbook.setVisible(false);
        pnelChart.gerargrafico();
        pnelChart.setVisible(true);
    }//GEN-LAST:event_btn_gerargraficoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGerente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameGerente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adicionar;
    public javax.swing.JButton btn_atendentes;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_excluir;
    private javax.swing.JButton btn_gerargrafico;
    private javax.swing.JButton btn_listar;
    private javax.swing.JButton btn_pdf;
    // End of variables declaration//GEN-END:variables
}
